# Generated by Django 3.2 on 2023-01-17 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Literary', 'Literary'), ('Mystery', 'Mystery'), ('Non-Fiction', 'Non-Fiction'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller')], max_length=20)),
                ('review', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
